project:
  type: website
  output-dir: docs

website:
  title: "Share on statistics topics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    math: mathjax

editor: visual

